config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

  resources :checks
  resources :obcs
  resources :vendors
  root to: 'vendors#index'
end

app/models/check.rb
class Check < ActiveRecord::Base

  has_many :obcs
  has_many :vendors

end

app/models/obc.rb
class Obc < ActiveRecord::Base

belongs_to :vendor
belongs_to :check

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

  has_many :obcs
  belongs_to :check

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_check, only: [:show, :edit, :update, :destroy]

  # GET /checks
  # GET /checks.json
  def index
    @checks = Check.all
  end

  # GET /checks/1
  # GET /checks/1.json
  def show
  end

  # GET /checks/new
  def new
    @check = Check.new
  end

  # GET /checks/1/edit
  def edit
  end

  # POST /checks
  # POST /checks.json
  def create
    @check = Check.new(check_params)

    @check.vendors.each do |vendor|
      ObcWorker.perform_async(vendor.id, @check.url)
    end

    respond_to do |format|
      if @check.save
        format.html { redirect_to @check, notice: 'Check was successfully created.' }
        format.json { render :show, status: :created, location: @check }
      else
        format.html { render :new }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checks/1
  # PATCH/PUT /checks/1.json
  def update
    respond_to do |format|
      if @check.update(check_params)
        format.html { redirect_to @check, notice: 'Check was successfully updated.' }
        format.json { render :show, status: :ok, location: @check }
      else
        format.html { render :edit }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checks/1
  # DELETE /checks/1.json
  def destroy
    @check.destroy
    respond_to do |format|
      format.html { redirect_to checks_url, notice: 'Check was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check
      @check = Check.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_params
      params.require(:check).permit(:name)
    end
end

app/controllers/obcs_controller.rb
class ObcsController < ApplicationController
  before_action :set_obc, only: [:show, :edit, :update, :destroy]

  # GET /obcs
  # GET /obcs.json
  def index
    @obcs = Obc.all
  end

  # GET /obcs/1
  # GET /obcs/1.json
  def show
  end

  # GET /obcs/new
  def new
    @obc = Obc.new
  end

  # GET /obcs/1/edit
  def edit
  end

  # POST /obcs
  # POST /obcs.json
  def create
    @obc = Obc.new(obc_params)

    respond_to do |format|
      if @obc.save
        format.html { redirect_to @obc, notice: 'Obc was successfully created.' }
        format.json { render :show, status: :created, location: @obc }
      else
        format.html { render :new }
        format.json { render json: @obc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /obcs/1
  # PATCH/PUT /obcs/1.json
  def update
    respond_to do |format|
      if @obc.update(obc_params)
        format.html { redirect_to @obc, notice: 'Obc was successfully updated.' }
        format.json { render :show, status: :ok, location: @obc }
      else
        format.html { render :edit }
        format.json { render json: @obc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /obcs/1
  # DELETE /obcs/1.json
  def destroy
    @obc.destroy
    respond_to do |format|
      format.html { redirect_to obcs_url, notice: 'Obc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_obc
      @obc = Obc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def obc_params
      params.require(:obc).permit(:landingpage, :first_level)
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:vendorid, :name, :url)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/obcs_helper.rb
module ObcsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/checks/_form.html.erb
<script>
  $(document).ready(function(){
    $('#selectExport').click(function() {
      $('.check_boxes.optional.export').prop('checked', true);
    });
  });
</script>

<%= simple_form_for(@check) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.input :url %>
  </div>

  <% Vendor.each_slice(3) do |slice| %>
    <div class="row">
      <% slice.each do |vendor| -%>
          <div class="col-md-4">
            <%= f.association :vendors, collection: Vendor.all, as: :check_boxes, label_method: :name, value_method: :id, label: false, input_html: { class: "vendor" } %>
          </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/checks/edit.html.erb
<h1>Editing Check</h1>

<%= render 'form' %>

<%= link_to 'Show', @check %> |
<%= link_to 'Back', checks_path %>

app/views/checks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Checks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checks.each do |check| %>
      <tr>
        <td><%= check.name %></td>
        <td><%= link_to 'Show', check %></td>
        <td><%= link_to 'Edit', edit_check_path(check) %></td>
        <td><%= link_to 'Destroy', check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check', new_check_path %>

app/views/checks/new.html.erb
<h1>New Check</h1>

<%= render 'form' %>

<%= link_to 'Back', checks_path %>

app/views/checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @check.name %>
</p>

<%= link_to 'Edit', edit_check_path(@check) %> |
<%= link_to 'Back', checks_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Händler', vendors_path %></li>
<li><%= link_to 'Neuer Check', new_check_path %></li>
<li><%= link_to 'Checks', checks_path %></li>
<li><%= link_to 'OBCs', obcs_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Crawler" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Crawler" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/obcs/_form.html.erb
<%= simple_form_for(@obc) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :landingpage %>
    <%= f.input :first_level %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/obcs/edit.html.erb
<h1>Editing Obc</h1>

<%= render 'form' %>

<%= link_to 'Show', @obc %> |
<%= link_to 'Back', obcs_path %>

app/views/obcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Obcs</h1>

<table>
  <thead>
    <tr>
      <th>Landingpage</th>
      <th>First level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @obcs.each do |obc| %>
      <tr>
        <td><%= obc.landingpage %></td>
        <td><%= obc.first_level %></td>
        <td><%= link_to 'Show', obc %></td>
        <td><%= link_to 'Edit', edit_obc_path(obc) %></td>
        <td><%= link_to 'Destroy', obc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Obc', new_obc_path %>

app/views/obcs/new.html.erb
<h1>New Obc</h1>

<%= render 'form' %>

<%= link_to 'Back', obcs_path %>

app/views/obcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Landingpage:</strong>
  <%= @obc.landingpage %>
</p>

<p>
  <strong>First level:</strong>
  <%= @obc.first_level %>
</p>

<%= link_to 'Edit', edit_obc_path(@obc) %> |
<%= link_to 'Back', obcs_path %>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/vendors/_form.html.erb
<%= simple_form_for(@vendor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :vendorid %>
    <%= f.input :name %>
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vendors</h1>

<table>
  <thead>
    <tr>
      <th>Vendorid</th>
      <th>Name</th>
      <th>Url</th>
      <th>Landingpage OBC</th>
      <th>First Level OBC</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.vendorid %></td>
        <td><%= vendor.name %></td>
        <td><%= vendor.url %></td>
        <td><%= vendor.obc.landingpage rescue 'No result' %></td>
        <td><%= vendor.obc.first_level rescue 'No result' %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vendorid:</strong>
  <%= @vendor.vendorid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @vendor.url %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>

app/views/visitors/index.html.erb
<h3>Welcome</h3>